name: Deploy to GitHub Pages
on:
push:
branches: [main, master, cosmos-home]
workflow_dispatch:
permissions:
contents: write
concurrency:
group: gh-pages
cancel-in-progress: true
jobs:
build-and-deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
with:
node-version: 18
cache: yarn
- run: corepack enable
- run: yarn install --immutable=false
- name: Build static app and Storybook
env:
NEXT_BASE_PATH: /${{ github.event.repository.name }}
NEXT_PUBLIC_SITE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
run: yarn build:pages
- run: touch out/.nojekyll
- uses: peaceiris/actions-gh-pages@v3
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
publish_dir: ./out
force_orphan: true
